language: ruby
rvm:
  - 1.8.7
  - ree
  - jruby-18mode

before_script: 
  - "sudo apt-get install libproj-dev libgeos-dev libsparsehash-dev libffi-dev "
script: "rake spec"
notifications:
  recipients:
    - luc.donnet@dryade.net