language: ruby
rvm:
  - 1.9.3
  - 1.8.7
  - jruby-18mode
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
matrix:
  exclude: 
    - rvm:  1.8.7
      jdk: openjdk7
    - rvm:  1.9.3
      jdk: openjdk7
    - rvm:  1.8.7
      jdk: oraclejdk7
    - rvm:  1.9.3
      jdk: oraclejdk7
before_install:
  - sudo apt-get update
  - sudo apt-get install libproj-dev libgeos-dev libffi-dev libsparsehash-dev
script: "rake spec"